### ISSUE TITLE
Lab Report 2 Grading

### ISSUE THREAD

**Issue by akanksha-maker-ucsd** [sunouray/cse15l-lab-reports#2]
**Bug/Input 1**
- [x] Commit screenshot for bug/input 1
- [x] Link to test file for bug/input 1
- [x] Symptom shown as command + output for bug/input 1
- [x] Description of relationship between bug, symptom, and input for bug/input 1

**Bug/Input 2**
- [x] Commit screenshot for bug/input 2
- [x] Link to test file for bug/input 2
- [x] Symptom shown as command + output for bug/input 2
- [x] Description of relationship between bug, symptom, and input for bug/input 2

**Bug/Input 3**
- [x] Commit screenshot for bug/input 3
- [x] Link to test file for bug/input 3
- [x] Symptom shown as command + output for bug/input 3
- [x] Description of relationship between bug, symptom, and input for bug/input 3

Additional comments from your grader:
Good job! This is very well-written but your images of the code diffs' images do not show up. 

Feel free to comment below if you have any questions about the rubric/feedback.

**Comment by raymosun** [comment]
Hi, do you mean screenshots of the commits of the breaking test files? Wasn't sure if the image was supposed to be of the problem commit or the fix commit.

**Comment by akanksha-maker-ucsd** [comment]
<img width="609" alt="Screen Shot 2022-02-06 at 3 01 05 AM" src="https://user-images.githubusercontent.com/78574543/152677751-d234e795-6704-4092-b16d-f68a37e5743d.png">
Hey! I just can't see the image of the code diffs.
